project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todos/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

project/todo/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    # GET /todos
    path('', views.index, name='index'),

    # GET /todos/1
    path('<int:todo_id>', views.todo, name='todo'),

    # PUT /todos/1/update
    path('<int:todo_id>/update/', views.update, name='update'),

    # POST /todos/create
    path('create/', views.create, name='create')
]

project/todo/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Todo(models.Model):
    description = models.CharField(max_length=250)
    created_at  = models.DateTimeField()
    updated_at  = models.DateTimeField()
    finished_at = models.DateTimeField(null=True)

    @classmethod
    def create(cls, description):
        todo = cls(description=description, created_at=datetime.now(), updated_at=datetime.now())
        todo.save()

    @classmethod
    def update_description(cls, description):
        cls.description = description
        cls.updated_at = datetime.now()

project/todo/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import Todo

# Create your views here.
def index(request):
    all_todos = Todo.objects.order_by('-created_at')
    template = loader.get_template('todos/index.html')
    context = {
        'all_todos': all_todos,
    }
    return HttpResponse(template.render(context, request))

def todo(request, todo_id):
    try:
        todo = Todo.objects.get(pk=todo_id)
    except Todo.DoesNotExist:
        raise Http404("Todo with the ID %s does not exist." % todo_id)
    return render(request, 'todos/todo.html', {'todo': todo})

def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    try:
        todo.update_description(description)
        todo.save()
        return HttpResponseRedirect(reverse('todos:todo', args=(todo.id,)))
    except(KeyError):
        return render(request, 'todos/todo.html', {
            'todo': todo,
            'error_message': 'You did not provide a description.'
        })

def create(request):
    try:
        new_todo = Todo.create(request.POST['description'])
        return HttpResponseRedirect(reverse('todos:index'))
    except KeyError:
        return render(request, 'todos/index.html', {
            'error_message': 'You did not provide a description.'  
        })

project/todo/templates/todos/index.html
{% if all_todos %}
    <ul>
    {% for todo in all_todos %}
        <li><a href="{% url 'todos:todo' todo.id %}">{{ todo.description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No todos are available.</p>
{% endif %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'todos:create' %}" method="post">
{% csrf_token %}
    <label for="description">
        <input type="text" name="description" id="description" placeholder="Name of new Todo">
    </label>
    <input type="submit" value="Create New Todo">
</form>

project/todo/templates/todos/todo.html
<h1>Todo: {{ todo.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
    <li>Description: {{ todo.description }}</li>
    <li>Created at: {{ todo.created_at|date:'r' }}</li>
    <li>Updated at: {{ todo.updated_at|date:'r' }}</li>
    <li>Finished at: {{ todo.finished_at|date:'r' }}</li>
</ul>


<form action="{% url 'todos:update' todo.id %}" method="post">
{% csrf_token %}
    <label for="description">
        <input type="text" name="description" id="description" value="{{ todo.description }}">
    </label>
    <input type="submit" value="Update">
</form>